### ISSUE TITLE
doesn't seem to work with DW 2015-08-10 "Detritus"

### ISSUE THREAD

**Issue by Poukram35** [michael-dev/dokuwikietherpadlite#14]
Hi,
dokuwikietherpadlite doesn't seem to work DW last version, 2015-08-10 "Detritus", I don't see any icon in toolbar...
Do you plan to update the plugin ? Because it seems to be very interesting and complementary to DW.

Thanks
Olivier

**Comment by michael-dev** [comment]
I'll likely update this plugin before I update my dokuwiki installations. Thought, there is no schedule. Patches welcomed.

**Comment by bobcanthelpyou** [comment]
@Poukram35 tested the latest stable release of Dokuwiki "Detritus" with the Etherpad-lite plugin, and it runs without issues. 

Do you use a special template? Which Etherpad-Lite version do you use? Could you check your Etherpad-Lite log, web server log and browser console for errors?

**Comment by Poukram35** [comment]
Hi,
I tested again with a clean installation of detritus. Now I can see the icon but when I click on the icon I have this error : "JSON response could not be decoded" (see the attached image)
![by default 2015-10-22 a 11 51 41](https://cloud.githubusercontent.com/assets/5887670/10662315/0276aac8-78b4-11e5-88f7-c1590161479c.png)

**Comment by bobcanthelpyou** [comment]
Maybe the APIKEY is not correct and also the "shared cookie-domain for etherpad lite" seems to be wrong (the reason for the document.domain error on the console)

My example dokuwikietherpadlite plugin config looks similar to:
![bildschirmfoto von 2015-10-22 12 20 27](https://cloud.githubusercontent.com/assets/4523264/10662890/b603caaa-78b7-11e5-813d-58ef02232bbb.png)

And what are your changes at the Etherpad-Lite config file?

**Comment by GreenItSolutions** [comment]
Hi all,
I resolve this issue by modifying parameter in dokuwiki configuration after basic installation : 
- Debian Jessie 8.0
- DokuWiki 2015-08-10a "Detritus"
- Etherpad-lite 1.2.13

- Install etherpad-lite like in github documentation
- make no change in apache config nor vhost
- test etherpad-lite with http://myhost.mydomain.tld:9001
- test eherpad API with http://myhost.mydomain.tld:9001/api -> you should obtain etherpad-lite version number

In DW config, etherpad-lite section

1) field plugin etherpadlite etherpadlite_url
- Insert http://myhost.mydomain.tld:9001 WITHOUT trailing slash

2) field plugin etherpadlite etherpadlite_apikey
- go to your server and search for a file named APIKEY.txt in the etherpad-lite install directory
- copy and paste the content of the file in this field

3) field plugin etherpadlite etherpadlite_group
- In Dokuwiki User administration, search the group name of the users authorized to use etherpad-lite
- In Dokuwiki, user's groups names are not in plural : basic groups are "admin" and "user" without "s"
- for global use of etherpad-lite, put user in this field

4) field plugin etherpadlite etherpadlite_domain
- put here the Full Qualifed Domain Name of etherpad-lite, like in point 1 but without http:// and port
- for me, it's myhost.mydomain.tld

5) Enjoy

**Comment by michael-dev** [comment]
With respect to etherpadlite_group configuration variable: It is not the dokuwiki group of users permitted to use this plugin. Instead, etherpadlite also has the concept of groups and a pad needs to be assigned to a group for some security features to work. So this is only configurable to be able to isolate users from different dokuwiki instances sharing a etherpad lite host.
