### ISSUE TITLE
Hide etherpad controls

### ISSUE THREAD

**Issue by rasos** [michael-dev/dokuwikietherpadlite#16]
We have successfully installed the dokuwikietherpadliteplugin on an older DokuWiki Adora Belle version (including ProxyPass and ProxyPassreverse) and the ep_iframeinsert plugin on an existing, open etherpad-lite (installed manually, which needed a chown on the plugin to make ep work again).

Now we have two formatting rows, see screenshot. 
![dokuwikietehrpadliteformattingdoubled](https://cloud.githubusercontent.com/assets/485723/19220154/d44a7362-8e26-11e6-8b3a-bd1791bbbee1.png)
Where would we need to add the parameter "showControls=false" in the API call, as described here, when calling it by URL: https://github.com/ether/etherpad-lite/wiki/Embed-Parameters

**Comment by michael-dev** [comment]
Please add this to action/etherpadlite.php function getPageInfo.

Thanks for pointing this out.

**Comment by michael-dev** [comment]
This is now configurable, as it also removes the history controls.
